### ISSUE TITLE
Migrating issues

### ISSUE THREAD

**Issue by Ahmedak88** [glennake/SRX-to-ASA-Converter#6]
The migration script is only migrating interfaces, services and objects. It isn't migrating routing, access polices and NAT policies. would you please help?

**Comment by glennake** [comment]
Hi, can you provide a sanitised configuration for testing this?

**Comment by Ahmedak88** [comment]
Please find attached and thank you very much for your help.
[config_modified.txt](https://github.com/glennake/SRX-to-ASA-Converter/files/5175750/config_modified.txt)

**Comment by Ahmedak88** [comment]
I resolved the issue. the issue was with junos services. you will have to migrate them manually first.
thank you!

**Comment by glennake** [comment]
Thanks for the configuration. There were a number of issues, including:

 * Missing default applications
 * No support for dns name address objects
 * No support for any-ipv4 and any-ipv6 default addresses

I have fixed these in commit 35fbd29ce4e78eeedc478750ad29235abea56203, if you can try converting your config again.
