### ISSUE TITLE
address set to object network conversion not working if the address-set has an ip in the name.

### ISSUE THREAD

**Issue by ismailsamatar** [glennake/SRX-to-ASA-Converter#7]
for example an address-set with the name NET_10.200.68.0-23_USER_VPN wont be converted to an network object but it will referenced under the object group.

**Comment by glennake** [comment]
Hi @ismailsamatar,

Thanks for raising, this should be fixed in the latest commit 150ee9c68779f0431ca4f6ffc3477eb6005f42e8.

Please test and confirm?

Thanks

**Comment by ismailsamatar** [comment]
@glennake It works thank you very much Sir !

**Comment by ismailsamatar** [comment]
@glennake what was the bug ?

**Comment by glennake** [comment]
@ismailsamatar thanks for confirming. The regex pattern used to match object names did not cater for periods/full stops.
